### ISSUE TITLE
"Speed: Fast" is too slow on 30 Hz display

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/metadisk#1]
The "Fast" speed setting has the disk spinning at about 5 RPM, which still feels very slow. This is on my new laptop, which should be able to handle pretty much anything you throw at it for 2D graphics, so I know it's not the platform specifically.

This is on Chrome, where I have a lot of windows and tabs open (though most of them are suspended). Trying the same thing on a fresh copy of Edge with a single tab open has the disk spinning at about 10 RPM. Is that affecting the speed of the animation? It really shouldn't be, as I have plenty of CPU and GPU capacity available, and Chrome runs each tab in a separate process, AFAIK. 

It appears to be connected to having an external display with a slower refresh rate (30 Hz, in my case). Edge showed similar behavior--faster on my laptop's display, slower on my TV. Firefox seemed to keep the same speed on both (fast enough).

**Comment by ProfessorO** [comment]
https://stackoverflow.com/questions/19395565/chrome-requestanimationframe-issues

**Comment by ProfessorO** [comment]
https://www.testufo.com/

**Comment by dakotacookenmaster** [comment]
I've increased the maximum speed to be 0.5x faster than it was, and all of the other speeds have increased accordingly. This may not be a good permanent solution (perhaps moving away from `requestAnimationFrame` to another technology would behoove the app in the future), however it does appear to be a decent patch. I'm going to close this issue for now, but feel free to reopen in the future if the behavior becomes worse.
