### ISSUE TITLE
Disk Full Error/Filename length

### ISSUE THREAD

**Issue by corbintheweiss** [dakotacookenmaster/metadisk#10]
When the disk is full, I would expect it to give an error when I try to add another file, but it simply gives the popup message, "Filenames must be 13 characters or less". 
This error was produced when I tried to enter a longer filename, and continued to be popped up every time I created a new file for the disk. When the disk was full it would still allow me to go through the process of creating a file, pop up the filename length error, and not add the file.

**Comment by dakotacookenmaster** [comment]
The error structure of the app has been drastically changed, and this will be resolved in the next release.
