### ISSUE TITLE
FSV Inode Bitmap Overview is always short 1 page

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/metadisk#7]
With a disk that has 1 KiB sectors, 1 sector per block, and 8 blocks per disk (on 1 track), the system allocates a single block for the inode bitmap (which is correct). It then shows a paging widget at the bottom of the view, which shows "< 1 2 3 4 5 ... 31 >". I confirmed that the last page is short of the 8192 bits that should be shown. This seems to be the case regardless of the size of the disk and the number of inode blocks.

**Comment by dakotacookenmaster** [comment]
This was an off-by-one error. Good catch. This has been fixed and will be visible in the next alpha deployment.
