### ISSUE TITLE
FSV Binary bitmap view 0 = MSb

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/metadisk#8]
In the Binary view of bitmaps (in the FSV), the lowest-numbered bit is shown as the most significant bit. Thus, a disk that's only using the first 4 data blocks has a value of "11110000" in the first byte of the data bitmap. That reads nicely left to right, but it's fairly unusual to have the MSb correspond with the lowest-numbered item. I'm OK leaving it this way, but the documentation should include a little diagram that makes that clear.

**Comment by dakotacookenmaster** [comment]
This is a good point! It's definitely an implementation and convention detail. I'm happy to document that.
